### PR TITLE
max filter time

### PR DESCRIPTION
**Pull request by RoyWilliams**
Puts the timeout on active filters into settings.py so it can be adjusted

### CODE REVIEW

**Comment by gpfrancis** [comment]
See my comment on #101

**Comment by RoyWilliams** [comment]
Yes I did what you suggested and still get a fail. Please can you reset my password so I can see Jenkins?

**Comment by gpfrancis** [comment]
Sorry, some of the failing tests were integration tests - so you need to make the same change in `tests/integration/pipeline/filter/settings.py`

**Comment by gpfrancis** [comment]
(or alternatively set `settings` in the test itself, or use `getattr` to access it in the code and set a default value)

**Review by gpfrancis — APPROVED** [review]
Looks good.

**Pull request merged**
